name: Deploy to Vercel

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    # Install dependencies
    - name: Install Dependencies
      run: npm ci
      
    # Create production environment file
    - name: Create Environment File
      run: |
        echo "NODE_ENV=production" >> .env.production
        echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" >> .env.production
        echo "NEXT_PUBLIC_WS_URL=${{ secrets.NEXT_PUBLIC_WS_URL }}" >> .env.production
        echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" >> .env.production
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.production
        echo "NEXT_PUBLIC_OPENAI_API_KEY=${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }}" >> .env.production
        echo "NEXT_PUBLIC_DEBUG=false" >> .env.production
        echo "NEXT_PUBLIC_FEATURE_REALTIME=true" >> .env.production
        echo "NEXT_PUBLIC_FEATURE_AI=true" >> .env.production
        
    # Run build
    - name: Build Application
      run: npm run build:vercel
      env:
        NODE_ENV: production
        NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
        NEXT_PUBLIC_WS_URL: ${{ secrets.NEXT_PUBLIC_WS_URL }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
    # Deploy to Vercel
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./
        
    # Notify deployment status
    - name: Deployment Success Notification
      if: success()
      run: |
        echo "🚀 Deployment to Vercel successful!"
        echo "✅ Frontend deployed at: https://rejlers-frontend.vercel.app/"
        
    - name: Deployment Failure Notification  
      if: failure()
      run: |
        echo "❌ Deployment to Vercel failed!"
        echo "Please check the logs above for error details."